{
 "title": "Current",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "InlfluxDB Stat Exporter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "qatarairways.com",
     "query": "SELECT * FROM \"rtt\" WHERE dst::tag = 'qatarairways.com'"
    },
    {
     "alias": "pornhub.com",
     "query": "SELECT * FROM \"rtt\" WHERE dst::tag = 'pornhub.com'"
    },
    {
     "alias": "1a.ee",
     "query": "SELECT * FROM \"rtt\" WHERE dst::tag = '1a.ee'"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bind9 Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bind9 Request Per Min",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx Request Per Min",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL Request Per Min",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Haproxy Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Haproxy Container vm 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"lb-1:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Haproxy Container vm 2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"lb-2:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Keep Alive Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "__auto" }
   ]
  }
 ]
}