- name: make user Agama
  ansible.builtin.user:
    name: agama

- name: Agama is owner now
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    group: agama
    mode: '0755'

- name: download phython3 flask sql
  ansible.builtin.apt:
    name: 
     - python3-flask-sqlalchemy
     - python3-pymysql
    state: present

- name: Download agama.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    mode: '0755'
