- name: Restart bind
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: rndc reload bind9
  ansible.builtin.command: rndc reload
  changed_when: true

- name: Restart exporter
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: restarted